
<?php
/**
 * Created by PhpStorm.
 * User: dknig
 * Date: 20/05/2017
 * Time: 7:04 PM
 */
    // Footer content
    echo "<div id=\"footer\"><br/><br/>";
    echo "<div id=\"footer-wrapper\">";
    echo "<div id=\"right-wrapper\">";
    echo "<p style=\"font-size: 1.3em;font-weight: bold\">About the website</p>";
    echo "<p id=\"about-description\">Search places from anytime and anywhere.</p>";
    echo "<p> Your journey to perfect trip begins here.</p><br/><br/>";
    echo "<p style=\"float:right\">Copyright & Designed by Patrick Leong and Ken Lau</p></div>";
    echo "<div id=\"left-wrapper\"><img src=\"img/main_logo.png\" alt=\"Company Logo\" title=\"Company Logo\" width=\"235\" height=\"125\"/>";
    echo "<p>Phone: 04226557554</p>";
    echo "<p> Email: dknight1938@hotmail.com</p></div></div></div>";
 ?>